# Sobre R

### ¿Qué es R?  
R es un lenguaje de programación y entorno de software especializado en análisis estadístico, ciencia de datos y visualización gráfica. Creado en la década de 1990, ha sido ampliamente adoptado en la academia, la investigación y la industria debido a su flexibilidad y la gran cantidad de paquetes disponibles.

### ¿Por qué R?  

* **Especialización en estadística y ciencia de datos:** R está diseñado específicamente para análisis estadístico y modelado de datos, lo que lo convierte en una opción ideal para científicos de datos y analistas.  

* **Gran cantidad de paquetes y comunidad activa:** R cuenta con una vasta colección de paquetes (como `ggplot2` para visualización, `dplyr` para manipulación de datos y `caret` para aprendizaje automático) que facilitan el análisis de datos. Además, su comunidad activa constantemente desarrolla y mejora nuevas herramientas.  

* **Visualización de datos poderosa:** Con bibliotecas como `ggplot2` y `shiny`, R permite crear gráficos detallados y aplicaciones interactivas sin necesidad de herramientas adicionales.  

* **Interoperabilidad:** R puede integrarse con otros lenguajes como Python, C y SQL, permitiendo un flujo de trabajo flexible para distintos tipos de proyectos.  

* **Lenguaje interpretado y dinámico:** R permite escribir y ejecutar código sin necesidad de compilación, lo que facilita la experimentación y exploración de datos de manera interactiva.  

Si buscas un lenguaje potente para estadística, ciencia de datos y visualización, R es una excelente opción.

# Variables

In [1]:
# Declaración sin especificar tipo:
nombre <- "Jose"
x <- 7
y <- 7.324
falso <- FALSE

# R es un lenguaje dinámicamente tipado, por lo que no es necesario especificar tipos explícitamente.
# Sin embargo, podemos forzar el tipo usando as.*() cuando sea necesario.

apellido <- as.character("SZ")
a <- as.integer(7)
b <- as.numeric(7.324)  # En R, los números decimales por defecto son de tipo double, pero sigue funcionando para float
opcion <- as.logical(FALSE)

# Uso de print y cat para impresión
print("hello")
print("hello")
cat("bye\n")  # cat no añade salto de línea automáticamente en cada impresión
cat("bye\n")
cat("what\n")

[1] "hello"
[1] "hello"
bye
bye
what


# Operaciones Aritméticas en R
R ofrece una variedad de operaciones aritméticas para realizar cálculos matemáticos con sus tipos de datos numéricos. Las principales operaciones aritméticas en R son:

Suma (+): Suma dos operandos.
Resta (-): Resta el segundo operando del primero.
Multiplicación (*): Multiplica dos operandos.
División (/): Divide el primer operando por el segundo.
Exponente (^ o **): Eleva el primer operando a la potencia del segundo.
Módulo (%%): Obtiene el residuo de la división del primer operando por el segundo.
División entera (%/%): Devuelve el cociente entero de la división.

In [2]:
# Suma
suma <- 4 + 5
print(suma)

# Resta
resta <- 10 - 8
print(resta)

# Multiplicación
multi <- 7 * 5
print(multi)

# División flotante
divisionf <- 25 / 5
print(divisionf)

# División entera
divisione <- 25 %/% 5
print(divisione)

# Potencia
expo <- 2 ^ 5  # También se puede usar 2 ** 5
print(expo)

# Módulo (residuo)
residuo <- 11 %% 3
print(residuo)

[1] 9
[1] 2
[1] 35
[1] 5
[1] 5
[1] 32
[1] 2


# Operadores Booleanos en R  

Los operadores booleanos son herramientas utilizadas para el control del flujo de ejecución de un programa o evaluar expresiones lógicas para determinar si son verdaderas o falsas.  

### **Operadores Lógicos**  
Evalúan si una expresión booleana es verdadera o falsa:  

* **Y (`&&`)**: Devuelve `TRUE` solo si ambas expresiones son `TRUE`.  
* **O (`||`)**: Devuelve `TRUE` si al menos una de las expresiones es `TRUE`.  
* **Not (`!`)**: Niega el valor de la expresión que le sigue.  

### **Operadores Relacionales**  
Comparan valores de distintos tipos:  

* **Igual (`==`)**: Verifica si dos valores son iguales.  
* **Distinto (`!=`)**: Verifica si un valor es distinto de otro.  
* **Menor que (`<`)**: Verifica si un valor es menor que otro.  
* **Menor o igual que (`<=`)**: Verifica si un valor es menor o igual que otro.  
* **Mayor que (`>`)**: Verifica si un valor es mayor que otro.  
* **Mayor o igual que (`>=`)**: Verifica si un valor es mayor o igual que otro.

In [3]:
# Ejemplos de Operadores Booleanos en R

# Lógicos

# Ejemplo de verificación "Y" y "O" de dos valores de tipo lógico
usuario <- TRUE
contra <- FALSE

# Verificación 1 (AND lógico)
verificacion <- usuario && contra
# Imprimimos el resultado
print(paste("Resultado:", verificacion))

# Verificación 2 (OR lógico)
verificacion2 <- usuario || contra
# Imprimimos el resultado
print(paste("Resultado:", verificacion2))

# Relacionales

# Comprobamos si 2 es mayor que 1
comprobar <- 2 > 1
print(paste("Es 2 mayor que 1?:", comprobar))

# Ahora comprobamos si 2 es menor que 1
comprobar <- 2 < 1
print(paste("Es 2 menor que 1?:", comprobar))

# Verificamos si dos valores son iguales
x <- 2
y <- 2

es_igual <- x == y
print(paste("Es x igual a y?:", es_igual))

[1] "Resultado: FALSE"
[1] "Resultado: TRUE"
[1] "Es 2 mayor que 1?: TRUE"
[1] "Es 2 menor que 1?: FALSE"
[1] "Es x igual a y?: TRUE"


# Ciclos


In [4]:
# Empieza en 1, incrementa de 2 en 2 hasta llegar a 10
for (i in seq(1, 10, by = 2)) {
  print(i)
}

# El while se ejecuta si la condición es verdadera
# La variable controladora del ciclo debe estar definida
j <- 0
while (j < 5) {
  print(j)
  j <- j + 1
}

[1] 1
[1] 3
[1] 5
[1] 7
[1] 9
[1] 0
[1] 1
[1] 2
[1] 3
[1] 4


# Estructuras de datos

In [5]:
# Un vector es una secuencia ordenada de elementos del mismo tipo. Es similar a una lista en Java.
# Una matriz es una colección bidimensional de elementos del mismo tipo, organizados en filas y columnas.

# Creando una matriz 2x3
matriz <- matrix(c(1, 2, 3, 4, 5, 6), nrow = 2, byrow = TRUE)
print(matriz)
cat("\n")
# Accediendo al elemento en la segunda fila, tercera columna
elemento <- matriz[2, 3]
print(elemento)
cat("\n")
# Transpuesta de una matriz
transpuesta <- t(matriz)
print(transpuesta)
cat("\n")
# Multiplicación de matrices
producto <- matriz %*% t(matriz)
print(producto)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6

[1] 6

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

     [,1] [,2]
[1,]   14   32
[2,]   32   77


# Funciones
Las funciones son bloques de código que pueden ser reutilizados.

Una función se define con la palabra clave function seguido del nombre de la función, los parámetros de entrada entre paréntesis seguido por el cuerpo de la función (identado).

In [6]:
# Definir la función suma
add <- function(a, b) {
  return(a + b)
}

# Usar la función suma
resultado <- add(2, 5)
print(paste("El resultado de la suma es:", resultado))

[1] "El resultado de la suma es: 7"


# Otros
---

### POO en R

- **S3:** Es el sistema más simple e informal, basado en convenciones. No tiene una declaración explícita de clases; basta con asignar un atributo "class" a un objeto y definir métodos genéricos que se comportan de forma diferente según la clase.
- **S4:** Es un sistema más formal y riguroso que permite declarar clases, especificar sus slots (atributos), y definir validaciones, además de soportar herencia entre clases.

---

### ¿Paradigmas de programación en R?

R es un lenguaje **multi-paradigma**. Entre los enfoques que admite se encuentran:

- **Programación funcional:** Las funciones son ciudadanos de primera clase y es muy común escribir código de forma funcional.
- **Programación orientada a objetos:** Mediante los sistemas S3, S4, Reference Classes y R6 se pueden aplicar conceptos de clases, objetos, herencia y polimorfismo.
- **Programación imperativa y procedural:** También se pueden escribir scripts y programas usando estructuras de control, asignaciones y procedimientos tradicionales.

---

### ¿Es R un lenguaje de scripting?

R es considerado un **lenguaje de scripting**. Es un lenguaje interpretado que se usa ampliamente para análisis estadístico, minería de datos y generación de gráficos. Se puede ejecutar de forma interactiva en la consola, en entornos de desarrollo integrados (como RStudio) o a través de scripts almacenados en archivos con extensión `.R`.

---

### ¿Cómo se ejecuta un código de R?

El código R puede ejecutarse de diversas maneras:

- **Interactivo:** Iniciando una sesión de R en la consola o mediante un IDE como RStudio, donde se pueden ejecutar líneas o bloques de código directamente.
- **Desde un script:** Guardando el código en un archivo con extensión `.R` y luego ejecutándolo usando la función `source("archivo.R")` dentro de una sesión de R.
- **Desde la línea de comandos:** Utilizando el comando `Rscript`. Por ejemplo:
  - `Rscript testScript.R` ejecuta el script en la terminal.

Esta flexibilidad permite que R se utilice tanto para tareas interactivas como para automatización a través de scripts.